package com.masterresponde.app;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Space;
import android.widget.TextView;
import android.widget.Toast;

public class NeonDashboardActivity extends Activity {
    private static final String PREFS="master_responde";
    private static final int BG=Color.rgb(1,5,9), CARD=Color.rgb(5,12,18), GREEN=Color.rgb(20,255,70), CYAN=Color.rgb(0,225,255), PURPLE=Color.rgb(210,45,255), RED=Color.rgb(255,45,80), MUTED=Color.rgb(160,172,182);
    private SharedPreferences prefs; private final Handler h=new Handler(Looper.getMainLooper());
    private TextView wa,acc,notif,engine,mode,lastChat,lastMsg,lastReply,lastStatus,pending,sent,fail,attempts,today,totalSent,rate,totalFail,online; private Button power;
    private final Runnable ticker=new Runnable(){public void run(){refresh();h.postDelayed(this,1500);}};
    @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences(PREFS,MODE_PRIVATE);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);setContentView(build());}
    @Override protected void onResume(){super.onResume();h.removeCallbacks(ticker);h.post(ticker);}@Override protected void onPause(){h.removeCallbacks(ticker);super.onPause();}

    private View build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(BG);LinearLayout root=col();root.setPadding(dp(16),dp(14),dp(16),dp(24));scroll.addView(root,new ViewGroup.LayoutParams(-1,-2));
        LinearLayout head=row();TextView menu=text("☰",30,CYAN,false);menu.setGravity(Gravity.CENTER);head.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(70)));TextView logo=text("▣",38,PURPLE,true);logo.setGravity(Gravity.CENTER);logo.setShadowLayer(16,0,0,PURPLE);head.addView(logo,new LinearLayout.LayoutParams(dp(65),dp(70)));TextView brand=text("MASTER\nRESPONDE",29,Color.WHITE,true);brand.setLineSpacing(0,.9f);head.addView(brand,new LinearLayout.LayoutParams(0,dp(70),1));LinearLayout rhs=col();TextView ver=text("v2.0.9",12,Color.WHITE,false);ver.setGravity(Gravity.RIGHT);rhs.addView(ver);online=text("● ONLINE",13,GREEN,true);online.setGravity(Gravity.RIGHT);rhs.addView(online);head.addView(rhs,new LinearLayout.LayoutParams(dp(92),-2));root.addView(head);
        TextView protect=text("✓   SOMENTE WHATSAPP BUSINESS     PROTEGIDO     🔒",13,Color.WHITE,true);protect.setGravity(Gravity.CENTER);protect.setPadding(dp(8),dp(13),dp(8),dp(13));protect.setBackground(bg(Color.rgb(2,19,12),GREEN,12,1));root.addView(protect,new ViewGroup.LayoutParams(-1,-2));
        title(root,"STATUS DOS SERVIÇOS");LinearLayout services=row();wa=service(services,"◉","WhatsApp\nBusiness",GREEN);acc=service(services,"♿","Acessibilidade",PURPLE);notif=service(services,"♧","Notificações",CYAN);engine=service(services,"⚙","Motor de\nRespostas",CYAN);root.addView(services);
        title(root,"CONTROLE DO BOT");LinearLayout control=card(GREEN);LinearLayout controls=row();Button start=action("▶  ATIVAR BOT",GREEN);start.setOnClickListener(v->{prefs.edit().putBoolean("bot_enabled",true).apply();refresh();});controls.addView(start,new LinearLayout.LayoutParams(0,dp(58),1));controls.addView(spaceH(12));FrameLayout center=new FrameLayout(this);power=new Button(this);power.setText("⏻");power.setTextSize(42);power.setTextColor(GREEN);power.setBackground(circle(Color.rgb(2,25,13),GREEN,3));power.setOnClickListener(v->{prefs.edit().putBoolean("bot_enabled",!prefs.getBoolean("bot_enabled",false)).apply();refresh();});FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(dp(112),dp(112),Gravity.CENTER);center.addView(power,pp);controls.addView(center,new LinearLayout.LayoutParams(dp(126),dp(118)));controls.addView(spaceH(12));Button pause=action("Ⅱ  PAUSAR BOT",RED);pause.setOnClickListener(v->{prefs.edit().putBoolean("bot_enabled",false).apply();refresh();});controls.addView(pause,new LinearLayout.LayoutParams(0,dp(58),1));control.addView(controls);LinearLayout modeRow=row();mode=text("MODO ATUAL: AUTOMÁTICO • ATIVO",12,GREEN,true);modeRow.addView(mode,new LinearLayout.LayoutParams(0,-2,1));TextView test=text("MODO TESTE   ●",12,MUTED,false);test.setGravity(Gravity.RIGHT);modeRow.addView(test,new LinearLayout.LayoutParams(0,-2,1));control.addView(modeRow);root.addView(control);
        title(root,"ATIVIDADE EM TEMPO REAL");LinearLayout activity=card(CYAN);LinearLayout atHead=row();atHead.addView(text("ATIVIDADE EM TEMPO REAL",12,Color.WHITE,true),new LinearLayout.LayoutParams(0,-2,1));TextView hist=text("VER HISTÓRICO",11,CYAN,true);hist.setOnClickListener(v->Toast.makeText(this,"Histórico será integrado nesta identidade Neon",Toast.LENGTH_SHORT).show());atHead.addView(hist);activity.addView(atHead);activity.addView(space(8));lastChat=activityRow(activity,"●","Última conversa:");lastMsg=activityRow(activity,"▣","Última mensagem:");lastReply=activityRow(activity,"➤","Última resposta:");lastStatus=activityRow(activity,"✓","Status:");root.addView(activity);
        LinearLayout duo=row();LinearLayout queue=card(PURPLE);queue.addView(text("FILA DE RESPOSTAS",12,Color.WHITE,true));pending=metric(queue,"•  Pendentes");sent=metric(queue,"•  Enviadas");fail=metric(queue,"•  Falhas");attempts=metric(queue,"•  Tentativas hoje");duo.addView(queue,new LinearLayout.LayoutParams(0,-2,1));duo.addView(spaceH(10));LinearLayout stats=card(CYAN);stats.addView(text("ESTATÍSTICAS HOJE",12,Color.WHITE,true));today=metric(stats,"›  Atendimentos");totalSent=metric(stats,"›  Respostas enviadas");rate=metric(stats,"›  Taxa de sucesso");totalFail=metric(stats,"›  Falhas");duo.addView(stats,new LinearLayout.LayoutParams(0,-2,1));root.addView(space(14));root.addView(duo);
        root.addView(space(14));LinearLayout security=card(GREEN);LinearLayout sec=row();TextView shield=text("🛡\n🔒",35,GREEN,true);shield.setGravity(Gravity.CENTER);shield.setShadowLayer(18,0,0,GREEN);sec.addView(shield,new LinearLayout.LayoutParams(dp(92),dp(125)));LinearLayout checks=col();checks.addView(text("SEGURANÇA MÁXIMA",14,Color.WHITE,true));checks.addView(space(8));checks.addView(text("✓  Somente WhatsApp Business (com.whatsapp.w4b)\n✓  Anti-eco ativo\n✓  Proteção contra conversa errada\n✓  Sistema anti-loop ativo",12,Color.WHITE,false));sec.addView(checks,new LinearLayout.LayoutParams(0,-2,1));TextView safe=text("100%\nSEGURO",18,GREEN,true);safe.setGravity(Gravity.CENTER);safe.setBackground(circle(Color.rgb(1,22,10),GREEN,2));sec.addView(safe,new LinearLayout.LayoutParams(dp(82),dp(82)));security.addView(sec);root.addView(security);
        root.addView(space(14));LinearLayout nav=card(CYAN);LinearLayout nr=row();nr.addView(nav("⌂\nINÍCIO",GREEN,v->scroll.smoothScrollTo(0,0)),weight());nr.addView(nav("▦\nCOMANDOS",Color.WHITE,v->openCommands()),weight());nr.addView(nav("◷\nHISTÓRICO",Color.WHITE,v->Toast.makeText(this,"Histórico em desenvolvimento",Toast.LENGTH_SHORT).show()),weight());nr.addView(nav("⚙\nCONFIGURAÇÕES",Color.WHITE,v->openSettings()),weight());nav.addView(nr);root.addView(nav);return scroll;}

    private void refresh(){boolean on=prefs.getBoolean("bot_enabled",false),bi=isBusinessInstalled(),ac=WhatsAppAccessibilityService.isEnabled(this),no=isNotificationAccessEnabled();set(wa,bi?"ATIVO":"OFF",bi);set(acc,ac?"ATIVA":"OFF",ac);set(notif,no?"ATIVAS":"OFF",no);set(engine,on?"ATIVO":"PAUSADO",on);mode.setText(on?"MODO ATUAL: AUTOMÁTICO • ATIVO":"MODO ATUAL: PAUSADO");mode.setTextColor(on?GREEN:RED);power.setTextColor(on?GREEN:RED);online.setText(on?"● ONLINE":"● PAUSADO");online.setTextColor(on?GREEN:RED);
        lastChat.setText(value(prefs.getString("accessibility_last_conversation","")));lastMsg.setText(value(prefs.getString("accessibility_last_message","")));lastReply.setText(value(prefs.getString("accessibility_last_reply",prefs.getString("accessibility_last_status",""))));lastStatus.setText(value(prefs.getString("accessibility_last_status","")));
        int p=prefs.getInt("neon_pending_replies",0),s=prefs.getInt("stats_sent_today",0),f=prefs.getInt("stats_failed_today",0),a=prefs.getInt("stats_attempts_today",s+f),t=prefs.getInt("stats_chats_today",a);pending.setText("•  Pendentes                         "+p);sent.setText("•  Enviadas                           "+s);fail.setText("•  Falhas                              "+f);attempts.setText("•  Tentativas hoje                 "+a);today.setText("›  Atendimentos                  "+t);totalSent.setText("›  Respostas enviadas          "+s);int r=(s+f)==0?0:Math.round(100f*s/(s+f));rate.setText("›  Taxa de sucesso              "+r+"%");totalFail.setText("›  Falhas                              "+f);}
    private void openSettings(){try{startActivity(new Intent(this,NeonSettingsActivity.class));}catch(Throwable e){Toast.makeText(this,"Configurações indisponíveis",Toast.LENGTH_SHORT).show();}} private void openCommands(){try{startActivity(new Intent(this,MessageSettingsActivity.class));}catch(Throwable e){Toast.makeText(this,"Comandos indisponíveis",Toast.LENGTH_SHORT).show();}}
    private TextView service(LinearLayout parent,String icon,String label,int accent){LinearLayout c=col();c.setGravity(Gravity.CENTER);c.setPadding(dp(5),dp(11),dp(5),dp(11));c.setBackground(bg(CARD,accent,12,1));TextView i=text(icon,29,accent,true);i.setGravity(Gravity.CENTER);i.setShadowLayer(12,0,0,accent);c.addView(i);TextView l=text(label,10,Color.WHITE,true);l.setGravity(Gravity.CENTER);c.addView(l);TextView state=text("...",10,GREEN,true);state.setGravity(Gravity.CENTER);c.addView(state);parent.addView(c,new LinearLayout.LayoutParams(0,dp(132),1));parent.addView(spaceH(7));return state;}
    private TextView activityRow(LinearLayout p,String icon,String label){LinearLayout r=row();TextView i=text(icon,15,CYAN,true);r.addView(i,new LinearLayout.LayoutParams(dp(24),-2));r.addView(text(label,11,MUTED,false),new LinearLayout.LayoutParams(dp(125),-2));TextView v=text("—",11,Color.WHITE,true);r.addView(v,new LinearLayout.LayoutParams(0,-2,1));p.addView(r);p.addView(space(7));return v;} private TextView metric(LinearLayout p,String label){TextView t=text(label,11,Color.WHITE,false);t.setPadding(0,dp(8),0,0);p.addView(t);return t;}
    private Button action(String s,int color){Button b=new Button(this);b.setText(s);b.setTextSize(12);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT_BOLD);b.setAllCaps(false);b.setBackground(bg(Color.argb(90,Color.red(color),Color.green(color),Color.blue(color)),color,10,2));return b;} private Button nav(String s,int color,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(10);b.setTextColor(color);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(l);return b;}
    private LinearLayout card(int accent){LinearLayout l=col();l.setPadding(dp(12),dp(12),dp(12),dp(12));l.setBackground(bg(CARD,accent,12,1));return l;} private void title(LinearLayout r,String s){r.addView(space(18));r.addView(text("-  "+s,12,Color.WHITE,true));r.addView(space(9));} private void set(TextView v,String s,boolean ok){v.setText(s);v.setTextColor(ok?GREEN:RED);} private boolean isBusinessInstalled(){try{getPackageManager().getPackageInfo("com.whatsapp.w4b",0);return true;}catch(Throwable t){return false;}} private boolean isNotificationAccessEnabled(){String e=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");return e!=null&&e.contains(getPackageName());}
    private GradientDrawable bg(int fill,int stroke,int radius,int width){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));d.setStroke(dp(width),stroke);return d;} private GradientDrawable circle(int fill,int stroke,int width){GradientDrawable d=bg(fill,stroke,100, width);d.setShape(GradientDrawable.OVAL);return d;} private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;} private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;} private TextView text(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return t;} private Space space(int x){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(x)));return s;} private Space spaceH(int x){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(dp(x),1));return s;} private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,dp(64),1);} private String value(String s){if(s==null||s.trim().isEmpty())return"—";s=s.trim();return s.length()>58?s.substring(0,55)+"...":s;} private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
}
