package com.masterresponde.app;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Space;
import android.widget.TextView;
import android.widget.Toast;

public class NeonDashboardActivity extends Activity {
 private static final String PREFS="master_responde"; private static final int BG=Color.rgb(1,5,9),CARD=Color.rgb(5,12,18),GREEN=Color.rgb(20,255,70),CYAN=Color.rgb(0,225,255),PURPLE=Color.rgb(210,45,255),RED=Color.rgb(255,45,80),MUTED=Color.rgb(160,172,182);
 private SharedPreferences prefs; private final Handler h=new Handler(Looper.getMainLooper()); private TextView wa,acc,notif,engine,mode,lastChat,lastMsg,lastReply,lastStatus,pending,sent,fail,attempts,today,totalSent,rate,totalFail,online; private Button power;
 private final Runnable ticker=new Runnable(){public void run(){try{refresh();}catch(Throwable ignored){}h.postDelayed(this,1500);}};
 @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences(PREFS,MODE_PRIVATE);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);try{View v=build();setContentView(v);}catch(Throwable e){setContentView(fallback(e));}}
 @Override protected void onResume(){super.onResume();h.removeCallbacks(ticker);h.post(ticker);}@Override protected void onPause(){h.removeCallbacks(ticker);super.onPause();}
 private View fallback(Throwable e){LinearLayout r=col();r.setPadding(dp(24),dp(30),dp(24),dp(30));r.setBackgroundColor(BG);r.addView(text("MASTER RESPONDE",30,Color.WHITE,true));r.addView(space(18));r.addView(text("PAINEL NEON",15,GREEN,true));r.addView(space(28));r.addView(text("O painel encontrou um erro visual e entrou no modo seguro.\n\nO motor de respostas não foi alterado.",15,Color.WHITE,false));r.addView(space(20));TextView d=text(e.getClass().getSimpleName()+": "+String.valueOf(e.getMessage()),11,RED,false);r.addView(d);return r;}
 private View build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(BG);LinearLayout root=col();root.setPadding(dp(16),dp(14),dp(16),dp(24));scroll.addView(root,new ScrollView.LayoutParams(-1,-2));
  LinearLayout head=row();TextView menu=text("☰",28,CYAN,false);menu.setGravity(Gravity.CENTER);head.addView(menu,new LinearLayout.LayoutParams(dp(45),dp(68)));TextView logo=text("▣",35,PURPLE,true);logo.setGravity(Gravity.CENTER);head.addView(logo,new LinearLayout.LayoutParams(dp(58),dp(68)));TextView brand=text("MASTER\nRESPONDE",27,Color.WHITE,true);head.addView(brand,new LinearLayout.LayoutParams(0,dp(68),1f));LinearLayout rhs=col();TextView ver=text("v2.0.9",11,Color.WHITE,false);ver.setGravity(Gravity.RIGHT);rhs.addView(ver);online=text("● ONLINE",12,GREEN,true);online.setGravity(Gravity.RIGHT);rhs.addView(online);head.addView(rhs,new LinearLayout.LayoutParams(dp(88),-2));root.addView(head);
  TextView protect=text("SOMENTE WHATSAPP BUSINESS     PROTEGIDO  🔒",12,Color.WHITE,true);protect.setGravity(Gravity.CENTER);protect.setPadding(dp(7),dp(12),dp(7),dp(12));protect.setBackground(bg(Color.rgb(2,19,12),GREEN,12,1));root.addView(protect,new LinearLayout.LayoutParams(-1,-2));
  title(root,"STATUS DOS SERVIÇOS");LinearLayout services=row();wa=service(services,"●","WhatsApp\nBusiness",GREEN);acc=service(services,"♿","Acessibilidade",PURPLE);notif=service(services,"♢","Notificações",CYAN);engine=service(services,"⚙","Motor de\nRespostas",CYAN);root.addView(services,new LinearLayout.LayoutParams(-1,-2));
  title(root,"CONTROLE DO BOT");LinearLayout control=card(GREEN);LinearLayout controls=row();Button start=action("ATIVAR BOT",GREEN);start.setOnClickListener(v->{prefs.edit().putBoolean("bot_enabled",true).apply();refresh();});controls.addView(start,new LinearLayout.LayoutParams(0,dp(56),1f));controls.addView(spaceH(8));FrameLayout center=new FrameLayout(this);power=new Button(this);power.setText("⏻");power.setTextSize(38);power.setTextColor(GREEN);power.setBackground(circle(Color.rgb(2,25,13),GREEN,3));power.setOnClickListener(v->{prefs.edit().putBoolean("bot_enabled",!prefs.getBoolean("bot_enabled",false)).apply();refresh();});center.addView(power,new FrameLayout.LayoutParams(dp(100),dp(100),Gravity.CENTER));controls.addView(center,new LinearLayout.LayoutParams(dp(110),dp(106)));controls.addView(spaceH(8));Button pause=action("PAUSAR BOT",RED);pause.setOnClickListener(v->{prefs.edit().putBoolean("bot_enabled",false).apply();refresh();});controls.addView(pause,new LinearLayout.LayoutParams(0,dp(56),1f));control.addView(controls);LinearLayout mr=row();mode=text("MODO ATUAL: AUTOMÁTICO",11,GREEN,true);mr.addView(mode,new LinearLayout.LayoutParams(0,-2,1f));TextView test=text("MODO TESTE  ○",11,MUTED,false);test.setGravity(Gravity.RIGHT);mr.addView(test,new LinearLayout.LayoutParams(0,-2,1f));control.addView(mr);root.addView(control,new LinearLayout.LayoutParams(-1,-2));
  title(root,"ATIVIDADE EM TEMPO REAL");LinearLayout activity=card(CYAN);lastChat=activityRow(activity,"Última conversa:");lastMsg=activityRow(activity,"Última mensagem:");lastReply=activityRow(activity,"Última resposta:");lastStatus=activityRow(activity,"Status:");root.addView(activity,new LinearLayout.LayoutParams(-1,-2));
  root.addView(space(14));LinearLayout duo=row();LinearLayout queue=card(PURPLE);queue.addView(text("FILA DE RESPOSTAS",12,Color.WHITE,true));pending=metric(queue,"Pendentes");sent=metric(queue,"Enviadas");fail=metric(queue,"Falhas");attempts=metric(queue,"Tentativas hoje");duo.addView(queue,new LinearLayout.LayoutParams(0,-2,1f));duo.addView(spaceH(8));LinearLayout stats=card(CYAN);stats.addView(text("ESTATÍSTICAS HOJE",12,Color.WHITE,true));today=metric(stats,"Atendimentos");totalSent=metric(stats,"Respostas enviadas");rate=metric(stats,"Taxa de sucesso");totalFail=metric(stats,"Falhas");duo.addView(stats,new LinearLayout.LayoutParams(0,-2,1f));root.addView(duo,new LinearLayout.LayoutParams(-1,-2));
  root.addView(space(14));LinearLayout security=card(GREEN);security.addView(text("🛡  SEGURANÇA MÁXIMA                         100% SEGURO",13,GREEN,true));security.addView(space(7));security.addView(text("✓ Somente WhatsApp Business (com.whatsapp.w4b)\n✓ Anti-eco ativo\n✓ Proteção contra conversa errada\n✓ Sistema anti-loop ativo",11,Color.WHITE,false));root.addView(security,new LinearLayout.LayoutParams(-1,-2));
  root.addView(space(14));LinearLayout nav=card(CYAN);LinearLayout nr=row();nr.addView(nav("⌂\nINÍCIO",GREEN,v->scroll.smoothScrollTo(0,0)),weight());nr.addView(nav("▦\nCOMANDOS",Color.WHITE,v->openCommands()),weight());nr.addView(nav("◷\nHISTÓRICO",Color.WHITE,v->Toast.makeText(this,"Histórico em desenvolvimento",Toast.LENGTH_SHORT).show()),weight());nr.addView(nav("⚙\nCONFIGURAÇÕES",Color.WHITE,v->openSettings()),weight());nav.addView(nr);root.addView(nav,new LinearLayout.LayoutParams(-1,-2));return scroll;}
 private void refresh(){if(prefs==null)return;boolean on=prefs.getBoolean("bot_enabled",false),bi=isBusinessInstalled(),ac=WhatsAppAccessibilityService.isEnabled(this),no=isNotificationAccessEnabled();set(wa,bi?"ATIVO":"OFF",bi);set(acc,ac?"ATIVA":"OFF",ac);set(notif,no?"ATIVAS":"OFF",no);set(engine,on?"ATIVO":"PAUSADO",on);if(mode!=null){mode.setText(on?"MODO ATUAL: AUTOMÁTICO • ATIVO":"MODO ATUAL: PAUSADO");mode.setTextColor(on?GREEN:RED);}if(power!=null)power.setTextColor(on?GREEN:RED);if(online!=null){online.setText(on?"● ONLINE":"● PAUSADO");online.setTextColor(on?GREEN:RED);}setValue(lastChat,prefs.getString("accessibility_last_conversation",""));setValue(lastMsg,prefs.getString("accessibility_last_message",""));setValue(lastReply,prefs.getString("accessibility_last_reply",prefs.getString("accessibility_last_status","")));setValue(lastStatus,prefs.getString("accessibility_last_status",""));int p=prefs.getInt("neon_pending_replies",0),s=prefs.getInt("stats_sent_today",0),f=prefs.getInt("stats_failed_today",0),a=prefs.getInt("stats_attempts_today",s+f),t=prefs.getInt("stats_chats_today",a);if(pending!=null)pending.setText("• Pendentes   "+p);if(sent!=null)sent.setText("• Enviadas   "+s);if(fail!=null)fail.setText("• Falhas   "+f);if(attempts!=null)attempts.setText("• Tentativas hoje   "+a);if(today!=null)today.setText("• Atendimentos   "+t);if(totalSent!=null)totalSent.setText("• Respostas enviadas   "+s);if(rate!=null)rate.setText("• Taxa de sucesso   "+((s+f)==0?0:Math.round(100f*s/(s+f)))+"%");if(totalFail!=null)totalFail.setText("• Falhas   "+f);}
 private void setValue(TextView v,String s){if(v!=null)v.setText(value(s));}private void openSettings(){try{startActivity(new Intent(this,NeonSettingsActivity.class));}catch(Throwable e){Toast.makeText(this,"Configurações indisponíveis",Toast.LENGTH_SHORT).show();}}private void openCommands(){try{startActivity(new Intent(this,MessageSettingsActivity.class));}catch(Throwable e){Toast.makeText(this,"Comandos indisponíveis",Toast.LENGTH_SHORT).show();}}
 private TextView service(LinearLayout p,String icon,String label,int accent){LinearLayout c=col();c.setGravity(Gravity.CENTER);c.setPadding(dp(4),dp(10),dp(4),dp(10));c.setBackground(bg(CARD,accent,12,1));TextView i=text(icon,26,accent,true);i.setGravity(Gravity.CENTER);c.addView(i);TextView l=text(label,9,Color.WHITE,true);l.setGravity(Gravity.CENTER);c.addView(l);TextView state=text("...",9,GREEN,true);state.setGravity(Gravity.CENTER);c.addView(state);p.addView(c,new LinearLayout.LayoutParams(0,dp(126),1f));p.addView(spaceH(5));return state;}private TextView activityRow(LinearLayout p,String label){LinearLayout r=row();r.addView(text(label,11,MUTED,false),new LinearLayout.LayoutParams(dp(125),-2));TextView v=text("—",11,Color.WHITE,true);r.addView(v,new LinearLayout.LayoutParams(0,-2,1f));p.addView(r);p.addView(space(7));return v;}private TextView metric(LinearLayout p,String s){TextView t=text("• "+s,10,Color.WHITE,false);t.setPadding(0,dp(8),0,0);p.addView(t);return t;}
 private Button action(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT_BOLD);b.setAllCaps(false);b.setBackground(bg(Color.rgb(8,20,16),c,10,2));return b;}private Button nav(String s,int c,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(9);b.setTextColor(c);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(l);return b;}private LinearLayout card(int accent){LinearLayout l=col();l.setPadding(dp(11),dp(11),dp(11),dp(11));l.setBackground(bg(CARD,accent,12,1));return l;}private void title(LinearLayout r,String s){r.addView(space(17));r.addView(text(s,12,Color.WHITE,true));r.addView(space(8));}private void set(TextView v,String s,boolean ok){if(v!=null){v.setText(s);v.setTextColor(ok?GREEN:RED);}}private boolean isBusinessInstalled(){try{getPackageManager().getPackageInfo("com.whatsapp.w4b",0);return true;}catch(Throwable t){return false;}}private boolean isNotificationAccessEnabled(){try{String e=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");return e!=null&&e.contains(getPackageName());}catch(Throwable t){return false;}}
 private GradientDrawable bg(int fill,int stroke,int radius,int width){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));d.setStroke(dp(width),stroke);return d;}private GradientDrawable circle(int fill,int stroke,int width){GradientDrawable d=bg(fill,stroke,100,width);d.setShape(GradientDrawable.OVAL);return d;}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}private TextView text(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return t;}private Space space(int x){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(x)));return s;}private Space spaceH(int x){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(dp(x),1));return s;}private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,dp(60),1f);}private String value(String s){if(s==null||s.trim().isEmpty())return"—";s=s.trim();return s.length()>58?s.substring(0,55)+"...":s;}private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
}
